import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';

const prisma = new PrismaClient();

/**
 * Script de Seed - Popular banco de dados com dados mock
 * 
 * Uso:
 *   npx tsx prisma/seed.ts
 *   ou
 *   npm run seed
 */

// Dados mock para projetos
const mockProjects = [
    {
        name: 'Estação Morumbi - Bloco A',
        description: 'Bloco A da estação Morumbi da linha 4-Amarela',
        bimPath: 'projects/seed/estacao_morumbi_bloco_a.ifc'
    },
    {
        name: 'Estação Butantã - Plataforma Central',
        description: 'Plataforma central da estação Butantã',
        bimPath: 'projects/seed/estacao_butanta_plataforma.obj'
    },
    {
        name: 'Estação Pinheiros - Acesso Norte',
        description: 'Acesso norte da estação Pinheiros',
        bimPath: 'projects/seed/estacao_pinheiros_acesso_norte.dwg'
    },
    {
        name: 'Estação Fradique Coutinho - Estrutura',
        description: 'Estrutura principal da estação Fradique Coutinho',
        bimPath: 'projects/seed/estacao_fradique_estrutura.ifc'
    },
    {
        name: 'Estação Faria Lima - Bloco Sul',
        description: 'Bloco sul da estação Faria Lima',
        bimPath: 'projects/seed/estacao_faria_lima_bloco_sul.obj'
    }
];

// Dados mock para registros
const mockRecordNames = [
    'Semana 1 - Fachada Principal',
    'Semana 2 - Estrutura Interna',
    'Semana 3 - Plataforma',
    'Semana 4 - Acesso Norte',
    'Semana 5 - Acesso Sul',
    'Semana 6 - Escadas',
    'Semana 7 - Elevadores',
    'Semana 8 - Finalização'
];

// Status possíveis para análises
const analysisStatuses = ['pending', 'processing', 'completed', 'failed'] as const;

/**
 * Criar diretórios necessários para arquivos mock
 */
function criarDiretoriosMock() {
    const uploadsDir = process.env.UPLOADS_DIR || './src/shared/data/uploads';
    const outputsDir = process.env.OUTPUTS_DIR || './src/shared/data/outputs';
    
    // Criar diretórios de projetos
    mockProjects.forEach((_, index) => {
        const projectId = index + 1;
        const projectUploadDir = path.join(uploadsDir, 'projects', projectId.toString());
        const projectOutputDir = path.join(outputsDir, projectId.toString());
        
        fs.mkdirSync(projectUploadDir, { recursive: true });
        fs.mkdirSync(projectOutputDir, { recursive: true });
        fs.mkdirSync(path.join(projectOutputDir, 'registros'), { recursive: true });
        fs.mkdirSync(path.join(projectOutputDir, 'analises'), { recursive: true });
    });
    
    // Criar diretório seed
    const seedDir = path.join(uploadsDir, 'projects', 'seed');
    fs.mkdirSync(seedDir, { recursive: true });
    
    console.log('✅ Diretórios criados');
}

/**
 * Criar arquivos BIM mock (arquivos vazios pequenos)
 */
function criarArquivosBimMock() {
    const uploadsDir = process.env.UPLOADS_DIR || './src/shared/data/uploads';
    
    mockProjects.forEach((project) => {
        const filePath = path.join(uploadsDir, project.bimPath);
        const dir = path.dirname(filePath);
        
        fs.mkdirSync(dir, { recursive: true });
        
        // Criar arquivo mock pequeno (apenas placeholder)
        fs.writeFileSync(filePath, `# Mock BIM file for ${project.name}\n# Generated by seed script\n`);
    });
    
    console.log('✅ Arquivos BIM mock criados');
}

/**
 * Gerar caminhos de fotos mock
 */
function gerarCaminhosFotos(projectId: number, recordId: number, quantidade: number = 5): string[] {
    return Array.from({ length: quantidade }, (_, i) => 
        `projects/${projectId}/records/${recordId}/foto_${i + 1}.jpg`
    );
}

/**
 * Criar análise mock com status específico
 */
function criarAnaliseMock(
    projectId: number,
    recordId: number,
    status: typeof analysisStatuses[number],
    index: number
) {
    const now = new Date();
    const baseData: any = {
        projectId,
        recordId,
        status,
        progress: 0,
        logs: [
            `═══════════════════════════════════════════════════════════`,
            `  🚀 ANÁLISE MOCK #${index + 1}`,
            `═══════════════════════════════════════════════════════════`,
            ``,
            `📦 Projeto ID: ${projectId}`,
            `📝 Registro ID: ${recordId}`,
            `📊 Status: ${status}`,
            ``
        ],
        outputPaths: {
            modelo3d: `${projectId}/registros/${recordId}/reconstrucao_${recordId}.ply`
        }
    };

    switch (status) {
        case 'pending':
            baseData.progress = 0;
            baseData.logs.push('⏳ Aguardando processamento...');
            break;

        case 'processing':
            baseData.progress = Math.floor(Math.random() * 80) + 10; // 10-90%
            baseData.startedAt = new Date(now.getTime() - 5 * 60 * 1000); // 5 min atrás
            baseData.logs.push(
                `🔄 Processamento em andamento...`,
                `📊 Progresso: ${baseData.progress}%`,
                `[Reconstrução 3D] ✅ Concluída`,
                `[Comparação C2C] 🔄 Em processamento...`
            );
            break;

        case 'completed':
            baseData.progress = 100;
            baseData.startedAt = new Date(now.getTime() - 10 * 60 * 1000); // 10 min atrás
            baseData.completedAt = now;
            baseData.resultPath = `${projectId}/analises/analysis_${index + 1}/comparacao_c2c.ply`;
            baseData.summaryJsonPath = `${projectId}/analises/analysis_${index + 1}/summary_c2c.json`;
            baseData.meanDistance = parseFloat((Math.random() * 5 + 1).toFixed(2)); // 1-6mm
            baseData.stdDeviation = parseFloat((Math.random() * 3 + 0.5).toFixed(2)); // 0.5-3.5mm
            baseData.logs.push(
                `✅ Processamento concluído com sucesso!`,
                `📊 Métricas:`,
                `   • Distância média: ${baseData.meanDistance}mm`,
                `   • Desvio padrão: ${baseData.stdDeviation}mm`,
                `📁 Arquivos gerados:`,
                `   • ${baseData.resultPath}`,
                `   • ${baseData.summaryJsonPath}`
            );
            break;

        case 'failed':
            baseData.progress = Math.floor(Math.random() * 60) + 20; // 20-80%
            baseData.startedAt = new Date(now.getTime() - 3 * 60 * 1000); // 3 min atrás
            baseData.error = 'Erro ao processar imagens: Falha na detecção de features';
            baseData.logs.push(
                `❌ Processamento falhou`,
                `⚠️ Erro: ${baseData.error}`,
                `📊 Progresso alcançado: ${baseData.progress}%`
            );
            break;
    }

    return baseData;
}

/**
 * Função principal de seed
 */
async function main() {
    console.log('🌱 Iniciando seed do banco de dados...\n');

    try {
        // Limpar banco (opcional - descomente se quiser resetar)
        // console.log('🗑️  Limpando banco de dados...');
        // await prisma.analysis.deleteMany();
        // await prisma.record.deleteMany();
        // await prisma.project.deleteMany();
        // console.log('✅ Banco limpo\n');

        // Criar diretórios e arquivos mock
        console.log('📁 Criando estrutura de diretórios...');
        criarDiretoriosMock();
        criarArquivosBimMock();
        console.log('');

        // Criar projetos
        console.log('📦 Criando projetos...');
        const projetos = [];
        for (const projectData of mockProjects) {
            try {
                const projeto = await prisma.project.create({
                    data: projectData
                });
                projetos.push(projeto);
                console.log(`   ✓ ${projeto.name} (ID: ${projeto.id})`);
            } catch (error: any) {
                if (error.code === 'P2002') {
                    // Projeto já existe, buscar existente
                    const existente = await prisma.project.findUnique({
                        where: { bimPath: projectData.bimPath }
                    });
                    if (existente) {
                        projetos.push(existente);
                        console.log(`   ⚠️  ${projectData.name} já existe (ID: ${existente.id})`);
                    }
                } else {
                    throw error;
                }
            }
        }
        console.log(`✅ ${projetos.length} projetos criados\n`);

        // Criar registros para cada projeto
        console.log('📝 Criando registros...');
        const registros: any[] = [];
        
        for (let i = 0; i < projetos.length; i++) {
            const projeto = projetos[i];
            const quantidadeRegistros = Math.floor(Math.random() * 3) + 2; // 2-4 registros por projeto
            
            for (let j = 0; j < quantidadeRegistros; j++) {
                const recordName = mockRecordNames[j % mockRecordNames.length];
                const fotosPaths = gerarCaminhosFotos(projeto.id, j + 1, 5);
                
                const record = await prisma.record.create({
                    data: {
                        name: `${recordName} - Projeto ${projeto.id}`,
                        projectId: projeto.id,
                        uploadedFilesPaths: fotosPaths,
                        recordPath: j % 2 === 0 
                            ? `${projeto.id}/registros/${j + 1}/reconstrucao_${j + 1}.ply`
                            : null // Alguns registros sem reconstrução ainda
                    }
                });
                
                registros.push({ ...record, projectId: projeto.id });
                console.log(`   ✓ ${record.name} (ID: ${record.id}, Projeto: ${projeto.id})`);
            }
        }
        console.log(`✅ ${registros.length} registros criados\n`);

        // Criar análises com diferentes status
        console.log('📊 Criando análises...');
        let analysisCount = 0;
        
        for (const registro of registros) {
            // Criar 1-2 análises por registro
            const quantidadeAnalises = Math.floor(Math.random() * 2) + 1;
            
            for (let k = 0; k < quantidadeAnalises; k++) {
                const statusIndex = analysisCount % analysisStatuses.length;
                const status = analysisStatuses[statusIndex];
                
                const analysisData = criarAnaliseMock(
                    registro.projectId,
                    registro.id,
                    status,
                    analysisCount
                );
                
                const analysis = await prisma.analysis.create({
                    data: analysisData
                });
                
                analysisCount++;
                console.log(`   ✓ Análise #${analysis.id} - Status: ${status} (Projeto: ${registro.projectId}, Registro: ${registro.id})`);
            }
        }
        console.log(`✅ ${analysisCount} análises criadas\n`);

        // Estatísticas finais
        console.log('═══════════════════════════════════════════════════════════');
        console.log('📊 Estatísticas do Seed:');
        console.log('═══════════════════════════════════════════════════════════');
        
        const totalProjects = await prisma.project.count();
        const totalRecords = await prisma.record.count();
        const totalAnalyses = await prisma.analysis.count();
        
        const analysesByStatus = await prisma.analysis.groupBy({
            by: ['status'],
            _count: true
        });
        
        console.log(`📦 Projetos: ${totalProjects}`);
        console.log(`📝 Registros: ${totalRecords}`);
        console.log(`📊 Análises: ${totalAnalyses}`);
        console.log('');
        console.log('📈 Análises por status:');
        analysesByStatus.forEach(({ status, _count }) => {
            console.log(`   • ${status}: ${_count}`);
        });
        
        console.log('');
        console.log('✅ Seed concluído com sucesso!');
        console.log('');
        console.log('💡 Próximos passos:');
        console.log('   1. Inicie o servidor: npm run dev');
        console.log('   2. Teste a API: curl http://localhost:3000/api/projects');
        console.log('   3. Veja análises: curl http://localhost:3000/api/analyses');
        
    } catch (error) {
        console.error('❌ Erro durante seed:', error);
        throw error;
    } finally {
        await prisma.$disconnect();
    }
}

// Executar seed
main()
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });

